/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EvidenceStoreInterface extends Interface {
    getFunction(nameOrSignature: "storeEvidence" | "verifyEvidence"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EvidenceAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'storeEvidence', values: [string, string]): string;
encodeFunctionData(functionFragment: 'verifyEvidence', values: [string]): string;

    decodeFunctionResult(functionFragment: 'storeEvidence', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyEvidence', data: BytesLike): Result;
  }

  
    export namespace EvidenceAddedEvent {
      export type InputTuple = [fileHash: string, ipfsCID: string, uploader: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [fileHash: string, ipfsCID: string, uploader: string, timestamp: bigint];
      export interface OutputObject {fileHash: string, ipfsCID: string, uploader: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EvidenceStore extends BaseContract {
    
    connect(runner?: ContractRunner | null): EvidenceStore;
    waitForDeployment(): Promise<this>;

    interface: EvidenceStoreInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    storeEvidence: TypedContractMethod<
      [_fileHash: string, _ipfsCID: string, ],
      [void],
      'nonpayable'
    >
    

    
    verifyEvidence: TypedContractMethod<
      [_fileHash: string, ],
      [[string, bigint, string]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'storeEvidence'): TypedContractMethod<
      [_fileHash: string, _ipfsCID: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyEvidence'): TypedContractMethod<
      [_fileHash: string, ],
      [[string, bigint, string]],
      'view'
    >;

    getEvent(key: 'EvidenceAdded'): TypedContractEvent<EvidenceAddedEvent.InputTuple, EvidenceAddedEvent.OutputTuple, EvidenceAddedEvent.OutputObject>;

    filters: {
      
      'EvidenceAdded(string,string,address,uint256)': TypedContractEvent<EvidenceAddedEvent.InputTuple, EvidenceAddedEvent.OutputTuple, EvidenceAddedEvent.OutputObject>;
      EvidenceAdded: TypedContractEvent<EvidenceAddedEvent.InputTuple, EvidenceAddedEvent.OutputTuple, EvidenceAddedEvent.OutputObject>;
    
    };
  }