/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as evidenceStoreSol from './EvidenceStore.sol/index.js';
export type { evidenceStoreSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { EvidenceStore } from './EvidenceStore.sol/EvidenceStore.js';
export { EvidenceStore__factory } from './factories/EvidenceStore.sol/EvidenceStore__factory.js';